### ISSUE TITLE
ServerKits v2.0 To-Do

### ISSUE THREAD

**Issue by Flavius12** [EvolSoft/ServerKits#3]
ServerKits v2.0 Upcoming Features:
- [x] Implement one-kit-per-life option
- [x] Implement kit time limit option
- [x] Possible implementation of enchantments and tags

**Comment by Pub4Game** [comment]
1)To add support for other economic plugins
2)Make support multiple languages

**Comment by Flavius12** [comment]
1. Other Economy plugins  **won't** be implemented except MassiveEconomy (don't worry, you'll love the new MassiveEconomy update)
2. Multiple languages need a big change of code and I don't have time to do this

**Comment by Pub4Game** [comment]
If I find the time, i will help with the language files next week
